version: '3.8'

networks:
  monit:

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data7:/var/lib/clickhouse
      # - ./configs/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.xml
      # - ./configs/clickhouse/clickhouse-users.xml:/etc/clickhouse-server/users.xml
      # - ./configs/clickhouse/clickhouse-cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      # - ./configs/clickhouse/clickhouse-storage.xml:/etc/clickhouse-server/config.d/storage.xml
      # - ./data/clickhouse/:/var/lib/clickhouse/
      # - ./configs/init-db.sql/:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - '8123:8123'
      - '9000:9000'      
    networks:
      - monit


  grafana:
    restart: on-failure
    image: grafana/grafana:latest
    volumes:
      # - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource,vertamedia-clickhouse-datasource,volkovlabs-form-panel,marcusolsson-dynamictext-panel
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: vertamedia-clickhouse-datasource
      GF_PANELS_DISABLE_SANITIZE_HTML: true
    ports:
      - "3001:3000"
    depends_on:
      - clickhouse
    networks:
      - monit
    # volumes:
     # - ./data/grafana:/var/lib/grafana

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    restart: on-failure
    user: '0:0' # required for logs
    volumes:
      - ./configs/uptrace/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - '4317:4317'
      - '4318:4318'
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - monit

  uptrace:
    image: 'uptrace/uptrace:1.4.8'
    #image: 'uptrace/uptrace-dev:latest'
    restart: on-failure
    volumes:
      - ./configs/uptrace/uptrace.yml:/etc/uptrace/uptrace.yml
    #environment:
    #  - DEBUG=2
    ports:
      - '14317:14317'
      - '14318:14318'
    networks:
      - monit
      
  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - 'pg_data4:/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    networks:
      - monit
      
      
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '8025:8025'
    networks:
      - monit

  vector:
    image: timberio/vector:0.28.X-alpine
    volumes:
      - ./configs/uptrace/vector.toml:/etc/vector/vector.toml:ro
    networks:
      - monit



volumes:
  ch_data7:
  pg_data4: