extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
  jaeger:
    protocols:
      grpc:
  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: uptrace
    password: uptrace
    databases:
      - uptrace
    tls:
      insecure: true
  prometheus/otelcol:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  resourcedetection:
    detectors: ['system']
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  otlp/uptrace:
    endpoint: uptrace:14317
    tls: { insecure: true }
    headers: { 'uptrace-dsn': 'http://hivecloud@observability.hivecloud.com.br:14317/2' }
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    database: default
    logs_table_name: logs
    ttl_days: 3
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
      
service:
  telemetry:
    metrics:
      address: ':8888'
  #   logs:
  #     level: DEBUG
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [otlp/uptrace]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/uptrace]
    metrics/hostmetrics:
      receivers: [hostmetrics, postgresql, prometheus/otelcol]
      processors: [batch, resourcedetection]
      exporters: [otlp/uptrace]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/uptrace, clickhouse]

  extensions: [health_check, pprof, zpages]
