# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:

#proprio prometheus
# - job_name: prometheus
  # scrape_interval: 15s
  # scrape_timeout: 10s
  # metrics_path: /metrics
  # scheme: http
  # static_configs:
  # - targets:
    # - prometheus:9090
    
- job_name: aggregated-metrics
  static_configs:
    - targets: ['opentelemetry-collector:8889'] # using the name of the OpenTelemetryCollector container defined in the docker compose file